# Generated by Django 5.0.2 on 2024-03-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminmodel',
            table='Admin_table',
        ),
        migrations.AlterModelTable(
            name='maincategorymodel',
            table='Maincategory_table',
        ),
        migrations.AlterModelTable(
            name='subcategorymodel',
            table='Subcategory_table',
        ),
    ]
